schema_name: 'DATA_LAKE'
table_name: '*'
source_conn_id: 'aws_conn'
events:
  BUY_TRANSACTIONS:
    stage_schema : 'DATA_LAKE'
    stage_name : 'STAGE_S3_DATA_LAKE_BUY_TRANSACTIONS'
    target_table : 'BUY_TRANSACTIONS'
    target_schema : 'DATA_LAKE'
    s3_source_pattern : '^.*buy\.transactions.*$'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/buy.transactions/'
    file_format : 'PARQUET'
  BUY_USER_EVENTS:
    stage_schema : 'DATA_LAKE'
    stage_name : 'STAGE_S3_DATA_LAKE_BUY_USER_EVENTS'
    target_table : 'BUY_USER_EVENTS'
    target_schema : 'DATA_LAKE'
    s3_source_pattern : '^.*buy\.user\-events.*$'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/buy.user-events/'
    file_format : 'PARQUET'
  BUY_TRANSACTION_CREATIONS:
    stage_schema : 'DATA_LAKE'
    stage_name : 'STAGE_S3_DATA_LAKE_BUY_TRANSACTION_CREATIONS'
    target_table : 'BUY_TRANSACTION_CREATIONS'
    target_schema : 'DATA_LAKE'
    s3_source_pattern : '^.*buy\.transaction\-creations.*$'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/buy.transaction-creations/'
    file_format : 'PARQUET'
  PAYMENTS_PAYMENTS:
    stage_schema : 'DATA_LAKE'
    stage_name : 'STAGE_S3_DATA_LAKE_PAYMENTS_PAYMENTS'
    target_table : 'PAYMENTS_PAYMENTS'
    target_schema : 'DATA_LAKE'
    s3_source_pattern : '^.*payments\.payments.*$'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/payments.payments/'
    file_format: 'PARQUET'
  COMPETITOR_QUOTES:
    stage_schema : 'DATA_LAKE'
    stage_name : 'STAGE_S3_DATA_LAKE_COMPETITORS_COMPETITOR_QUOTES'
    target_table : 'COMPETITORS_COMPETITOR_QUOTES'
    target_schema : 'DATA_LAKE'
    s3_source_pattern : '^.*competitors\.competitor\-quotes.*$'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/competitors.competitor-quotes/'
  BUY_USER_INTERACTION_EVENTS:
    stage_schema : 'DATA_LAKE'
    stage_name : 'STAGE_S3_DATA_LAKE_BUY_USER_INTERACTION_EVENTS'
    target_table : 'BUY_USER_INTERACTION_EVENTS'
    target_schema : 'DATA_LAKE'
    s3_source_pattern : '^.*buy\.user\-interaction\-events.*$'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/buy.user-interaction-events/'
  SELL_KYC_INQUIRIES:
    stage_schema: 'DATA_LAKE'
    stage_name: 'STAGE_S3_DATA_LAKE_KYC_INQUIRIES'
    target_table: 'SELL_KYC_INQUIRIES'
    target_schema: 'DATA_LAKE'
    s3_source_pattern: '^kyc\.inquiries.*'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/kyc.inquiries/'
  SELL_CHECKOUT_CRYPTO_TRANSFERS:
    stage_schema: 'DATA_LAKE'
    stage_name: 'STAGE_S3_DATA_LAKE_SELL_CHECKOUT_CRYPTO_TRANSFERS'
    target_table: 'SELL_CHECKOUT_CRYPTO_TRANSFERS'
    target_schema: 'DATA_LAKE'
    s3_source_pattern: '.*'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/sell-checkout.crypto-transfers/'
  SELL_CHECKOUT_PAYMENT_INSTRUMENTS:
    stage_schema: 'DATA_LAKE'
    stage_name: 'STAGE_S3_DATA_LAKE_SELL_CHECKOUT_PAYMENT_INSTRUMENTS'
    target_table: 'SELL_CHECKOUT_PAYMENT_INSTRUMENTS'
    target_schema: 'DATA_LAKE'
    s3_source_pattern: '.*'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/sell-checkout.payment-instruments/'
  SELL_CHECKOUT_TRANSACTIONS:
    stage_schema: 'DATA_LAKE'
    stage_name: 'STAGE_S3_DATA_LAKE_SELL_CHECKOUT_TRANSACTIONS'
    target_table: 'SELL_CHECKOUT_TRANSACTIONS'
    target_schema: 'DATA_LAKE'
    s3_source_pattern: '.*'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/sell-checkout.transactions/'
  SELL_CHECKOUT_FIAT_PAYOUTS:
    stage_schema: 'DATA_LAKE'
    stage_name: 'STAGE_S3_DATA_LAKE_SELL_CHECKOUT_FIAT_PAYOUTS'
    target_table: 'SELL_CHECKOUT_FIAT_PAYOUTS'
    target_schema: 'DATA_LAKE'
    s3_source_pattern: '.*'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/sell-checkout.fiat-payouts/'
  SELL_CHECKOUT_CRYPTO_LIQUIDATIONS:
    stage_schema: 'DATA_LAKE'
    stage_name: 'STAGE_S3_DATA_LAKE_SELL_CHECKOUT_CRYPTO_LIQUIDATIONS'
    target_table: 'SELL_CHECKOUT_CRYPTO_LIQUIDATIONS'
    target_schema: 'DATA_LAKE'
    s3_source_pattern: '.*'
    file_format: 'PARQUET'
    s3_path: 's3://data-lake-simplex/operational-zone/raw/sell-checkout.crypto-liquidations/'