'ENRICH_EMAIL_AGE':
  table: "ENRICH_EMAIL_AGE"
'ENRICH_MAXMIND':
  table: "ENRICH_MAXMIND"
'MAXMIND_TRIGGERS':
  table: "MAXMIND_TRIGGERS"
'R_PAYMENTS':
  table: "R_PAYMENTS"
'QUOTES_DUPS':
  table: "QUOTES_DUPS"
'PAYMENT_EVENTS_LOG_REUPLOAD':
  table: "PAYMENT_EVENTS_LOG_REUPLOAD"
'R_PAYMENT_EXTERNAL_ALERTS':
  table: "R_PAYMENT_EXTERNAL_ALERTS"
'CHARGEBACKS':
  table: "CHARGEBACKS"
'CREDIT_CARDS_BASE':
  table: "CREDIT_CARDS_BASE"
'FEE_STRATEGIES':
  table: "FEE_STRATEGIES"
'VERIFICATION_REQUEST_INQUIRIES_CHECKS':
  table: "VERIFICATION_REQUEST_INQUIRIES_CHECKS"
'VERIFICATION_REQUEST_INQUIRIES':
  table: "VERIFICATION_REQUEST_INQUIRIES"
'USERS':
  table: "USERS"
'SIMPLEX_END_USERS':
  table: "SIMPLEX_END_USERS"
'R_PAYMENTS_ANALYTIC_TAGS':
  table: "R_PAYMENTS_ANALYTIC_TAGS"
'R_PAYMENT_EVENTS':
  table: "R_PAYMENT_EVENTS"
'R_PARTNER_DECISION_EVENTS':
  table: "R_PARTNER_DECISION_EVENTS"
'PROCESSORS':
  table: "PROCESSORS"
'CHARGEBACK_TYPES':
  table: "CHARGEBACK_TYPES"
'CHARGEBACK_DECISIONS':
  table: "CHARGEBACK_DECISIONS"
'PARTNER_END_USER_EMAILS':
  table: "PARTNER_END_USER_EMAILS"
'PAYMENT_LOCAL_CURRENCIES':
  table: "PAYMENT_LOCAL_CURRENCIES"
'PAYMENT_LOCALES':
  table: "PAYMENT_LOCALES"
'PAYMENT_STATUS_LOG':
  table: "PAYMENT_STATUS_LOG"
'UPLOADS':
  table: "UPLOADS"
'DUMMY_SOURCE':
  table: "DUMMY_SOURCE"
'ETL_LOGS':
  table: "ETL_LOGS"
'RAW_SOURCE':
  table: "RAW_SOURCE"
'THREEDS_VERSIONING_REQUESTS':
  table: "THREEDS_VERSIONING_REQUESTS"
'AB_TEST_DECISIONS':
  table: "AB_TEST_DECISIONS"



